# Generated by Django 4.2.7 on 2023-11-28 17:38

from django.db import migrations
import phonenumbers

def convert_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat',)
    flat_set = Flat.objects.all()
    if flat_set.exists():
        for flat in flat_set.iterator():
            number = phonenumbers.parse(flat.owners_phonenumber, "RU")
            flat.owner_pure_phone = None
            if phonenumbers.is_valid_number(number):
                flat.owner_pure_phone = phonenumbers.format_number(
                    number, phonenumbers.PhoneNumberFormat.E164
                )
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_flat_active_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_phonenumbers),
    ]
