# Generated by Django 4.2.7 on 2023-12-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_complaint_flat_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owned_apartments',
            field=models.ManyToManyField(related_name='owned_by', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
