# Generated by Django 4.2.7 on 2023-12-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_owner_owned_apartments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_apartments',
            new_name='apartments',
        ),
    ]
